# Generated by Django 6.0.4 on 2026-04-23 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('espece', models.CharField(choices=[('forastero', 'Forastero'), ('trinitario', 'Trinitario'), ('criollo', 'Criollo'), ('arabica', 'Arabica'), ('robusta', 'Robusta')], max_length=20)),
                ('poids_kg', models.FloatField()),
                ('gps_latitude', models.FloatField()),
                ('gps_longitude', models.FloatField()),
                ('date_recolte', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lots/')),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('cree', 'Créé'), ('en_transit', 'En transit'), ('certifie', 'Certifié'), ('exporte', 'Exporté')], default='cree', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
