# Generated by Django 6.0.4 on 2026-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
