# Generated by Django 6.0.4 on 2026-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='lot',
            name='certificat_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='data_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lot',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
