# Generated by Django 6.0.4 on 2026-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_remove_lot_qr_code_lot_certificat_url_lot_data_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='blockchain_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
