# Generated by Django 6.0.4 on 2026-04-23 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('ferme_cooperative', 'Ferme → Coopérative'), ('cooperative_transformateur', 'Coopérative → Transformateur'), ('transformateur_exportateur', 'Transformateur → Exportateur'), ('exportateur_europe', 'Exportateur → Europe')], max_length=40)),
                ('poids_verifie', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='lots.lot')),
            ],
        ),
    ]
